### ISSUE TITLE
Redesign do site

### ISSUE THREAD

**Issue by jeovazero** [lambda-study-group/lambda-study-group.github.io#3]
Segue o link da minha proposta de redesign:

https://www.figma.com/proto/kRQa0dKIkLGkpozGSSmN9H/lamda-study-group?node-id=1%3A2&scaling=scale-down-width

![Screenshot_2019-10-07 Figma](https://user-images.githubusercontent.com/11683201/66331043-0dad9280-e908-11e9-9956-fcedfb5bee8c.png)

Se aprovado, eu gostaria de implementá-lo em Elm :purple_heart:, tenho algumas ideias de animação das letras do combinadores que não consegui expressar no figma por algumas limitações.

Se não aprovarem, de boas, só vou mandar um foto do suicidal-pepe, huehuebr. :trollface: 

@anabastos @souenzzo @v0idpwn

**Comment by souenzzo** [comment]
Curti. Aproveitando a thread, Vamos reimplementar o site em HTML/CSS simples?
Quando houver funcionalidades que REALMENTE demandarem programação, fazemos em uma linguagem funcional qualquer (talvez até ES6)

**Comment by jeovazero** [comment]
Ah, pra mim tanto faz. Tenho preferência em fazer em Elm, mas o que vocês decidirem tô dentro.

**Comment by v0idpwn** [comment]
Eu voto por manter em Elm, motivo: pretendo escrever uma API pra interagir
com o lambdinha e talvez com o github num futuro próximo.

Em seg, 7 de out de 2019 15:36, jeovazero <notifications@github.com>
escreveu:

**Comment by v0idpwn** [comment]
Ademais, aprovo totalmente :)

**Comment by anabastos** [comment]
Realmente muito bom. Obrigada pela sugestão

**Comment by jeovazero** [comment]
Valeu. Já comecei, https://github.com/jeovazero/lambda-study-group.github.io/commit/7a34bfd0998310ab035c097e323fe6ad58f21821, hahaaha. Talvez saia ainda nessa semana...
